### ISSUE TITLE
Checklist Submission - Code Review 1

### ISSUE THREAD

**Issue by meglou752** [meglou752/SEM-Group-Project#8]
*We can delete this prior to code review, purely for our use*
- [x] GitHub project set up
- [x] Product Backlog created
- [x] Project builds to self-contained JAR with Maven
- [x] Dockerfile set up and fully functional
- [x] GitHub Actions for project set up
- [x] Correct branches for GitFlow created
- [ ] First release created
- [x] Code of Conduct defined
- [ ] Use cases and diagrams created
- [x] Issues, Kanban board and user stories defined
